### ISSUE TITLE
Exception was thrown but resources were created.

### ISSUE THREAD

**Issue by miaosakurai** [Microsoft/spring-cloud-azure#109]
Following exception thrown by illegal naming:

> java.lang.IllegalArgumentException: EventHub names must conform to the following rules to be able to use it with EventProcessorHost: Must start with a letter or number, and can contain only letters, numbers, and the dash (-) character. Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted in container names. All letters in a container name must be lowercase. Must be from 3 to 63 characters long.

But the event hub instances can still be created.

**Comment by warrenzhu25** [comment]
Could you put full details of stacktrace here? And as I remember, this is not only for event hub. List all related resource.

**Comment by yaweiw** [comment]
I can repro the problem:
Caused by: java.lang.IllegalArgumentException: EventHub names must conform to the following rules to be able to use it with EventProcessorHost: Must start with a letter or number, and can contain only letters, numbers, and the dash (-) character. Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted in container names. All letters in a container name must be lowercase. Must be from 3 to 63 characters long.
	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.initialize(AzureStorageCheckpointLeaseManager.java:112)
	at com.microsoft.azure.eventprocessorhost.EventProcessorHost.registerEventProcessorFactory(EventProcessorHost.java:464)
	at com.microsoft.azure.eventprocessorhost.EventProcessorHost.registerEventProcessorFactory(EventProcessorHost.java:424)
	at com.microsoft.azure.spring.integration.eventhub.EventHubTemplate.lambda$subscribe$1(EventHubTemplate.java:100)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.microsoft.azure.spring.integration.eventhub.EventHubTemplate.subscribe(EventHubTemplate.java:97)
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.doStart(AbstractInboundChannelAdapter.java:47)
	at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:162)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:285)

Looks like a bug with event hub sdk. As a workaround, we need to do some validation before this:
return azure.eventHubs().define(namespaceAndName.getSecond()).withExistingNamespace(eventHubNamespace).create();

**Comment by Incarnation-p-lee** [comment]
Just FYI, I also notice that not all azure resource name allows dash(-).

**Comment by warrenzhu25** [comment]
What we can do this is validate name before sending the request.
