### ISSUE TITLE
The messaging entity "xxx" could not be found

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/spring-cloud-azure#234]
I run into this issue when testing the spring-cloud-azure-eventhub-integration-sample using exising Event Hub namespace and Storage account. I'm using the basic tier. 

--- Logs --- 

[main] INFO example.EventHubIntegrationApplication - Started EventHubIntegrationApplication in 16.925 seconds (JVM running for 38.331)
[pool-10-thread-3] INFO com.microsoft.azure.eventhubs.impl.ConnectionHandler - onConnectionRemoteOpen: hostname[testspringone.servicebus.windows.net:5671, f64dadec3f3e472392c2e9891967d8c5_G25]
[pool-10-thread-3] INFO com.microsoft.azure.eventhubs.impl.ReceiveLinkHandler - linkName[mgmt:receiver], localSource[Source{address='$management', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}]
[pool-10-thread-3] INFO com.microsoft.azure.eventhubs.impl.SessionHandler - entityName[mgmt-session], sessionIncCapacity[0], sessionOutgoingWindow[2147483647]
[pool-10-thread-4] INFO com.microsoft.azure.eventhubs.impl.SendLinkHandler - linkName[mgmt:sender], remoteTarget[Target{address='$management', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}]
[pool-10-thread-4] INFO com.microsoft.azure.eventhubs.impl.ReceiveLinkHandler - linkName[mgmt:receiver], remoteSource[Source{address='$management', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}]
[pool-10-thread-6] ERROR com.microsoft.azure.eventprocessorhost.PartitionManager - host cn-yidon-327-10e45a66-2ade-48aa-9d84-227d5c0f6488: Exception while initializing stores, not starting partition manager
**com.microsoft.azure.eventhubs.IllegalEntityException: The messaging entity 'sb://testspringone.servicebus.windows.net/eventhub' could not be found.**
        at com.microsoft.azure.eventhubs.impl.ExceptionUtil.amqpResponseCodeToException(ExceptionUtil.java:71)
        at com.microsoft.azure.eventhubs.impl.ManagementChannel$1$1.onComplete(ManagementChannel.java:59)
        at com.microsoft.azure.eventhubs.impl.ManagementChannel$1$1.onComplete(ManagementChannel.java:47)
        at com.microsoft.azure.eventhubs.impl.RequestResponseChannel$ResponseHandler.onReceiveComplete(RequestResponseChannel.java:228)
        at com.microsoft.azure.eventhubs.impl.ReceiveLinkHandler.onDelivery(ReceiveLinkHandler.java:85)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:185)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
        at com.microsoft.azure.eventhubs.impl.MessagingFactory$RunReactor.run(MessagingFactory.java:445)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sophiaso** [comment]
Both happened for `spring-cloud-azure-eventhub-integration-sample` and `spring-cloud-azure-eventhub-operation-sample`.

No related error  log printed for [spring-cloud-azure-eventhub-operation-sample](https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/spring-cloud-azure-eventhub-operation-sample)

**Comment by warrenzhu25** [comment]
Event hub name should be changed into a existing event hub. Same as service bus. Will update the doc.
