### ISSUE TITLE
Redis cache sample timeout

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/spring-cloud-azure#235]
## Expected Behavior
* Show the message on web page

## Current Behavior
* Time out exception
```
Sep 11, 2018 4:03:07 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.data.redis.RedisConnectionFailureException: Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to  xxx.redis.cache.windows.net:6380] with root cause
io.netty.channel.ConnectTimeoutException: connection timed out: xxxx.redis.cache.windows.net/104.42.253.131:6380
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:125)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

## Possible Solution
* Provide timeout configuration

## Steps to Reproduce (for bugs)
* Configure properties
* Start CacheApplication
* Access http://localhost:8080/test
* 500 with server error

## Snapshot Code for Reproduce 
Redis cache sample code

## Branch
* master

## Your Environment
* Version used: snapshot
* Operating System and version (desktop or mobile): Windows 10
* SDK version: 1.8

**Comment by warrenzhu25** [comment]
This is a known issue. same as #117
