### ISSUE TITLE
Failed to checkpoint "Consume in earliest startPosition"

### ISSUE THREAD

**Issue by sophiaso** [microsoft/spring-cloud-azure#375]
Seems one message failed to be checkpointed. Don't know how to reproduce.

```
2018-12-11 15:58:05.274  WARN 15840 --- [pool-2-thread-6] c.m.a.s.i.e.i.EventHubCheckpointManager  : Consumer group 'xxxxxxxxxx' failed to checkpoint {body=hello batch mode message169, offset=4608, sequenceNumber=44, enqueuedTime=2018-12-11T07:37:47.012Z} on partition 2

java.util.concurrent.CompletionException: com.microsoft.azure.eventprocessorhost.ExceptionWithAction: com.microsoft.azure.storage.StorageException: The MD5 value specified in the request did not match with the MD5 value calculated by the server.
	at com.microsoft.azure.eventprocessorhost.LoggingUtils.wrapException(LoggingUtils.java:20) ~[azure-eventhubs-eph-1.0.0.jar:na]
	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.lambda$updateLeaseInternal$23(AzureStorageCheckpointLeaseManager.java:758) ~[azure-eventhubs-eph-1.0.0.jar:na]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[na:1.8.0_191]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[na:1.8.0_191]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
Caused by: com.microsoft.azure.eventprocessorhost.ExceptionWithAction: com.microsoft.azure.storage.StorageException: The MD5 value specified in the request did not match with the MD5 value calculated by the server.
	... 12 common frames omitted
Caused by: com.microsoft.azure.storage.StorageException: The MD5 value specified in the request did not match with the MD5 value calculated by the server.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89) ~[azure-storage-6.1.0.jar:na]
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315) ~[azure-storage-6.1.0.jar:na]
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175) ~[azure-storage-6.1.0.jar:na]
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:883) ~[azure-storage-6.1.0.jar:na]
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:713) ~[azure-storage-6.1.0.jar:na]
	at com.microsoft.azure.storage.blob.CloudBlob.uploadFromByteArray(CloudBlob.java:1726) ~[azure-storage-6.1.0.jar:na]
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadText(CloudBlockBlob.java:1176) ~[azure-storage-6.1.0.jar:na]
	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.uploadLease(AzureStorageCheckpointLeaseManager.java:811) ~[azure-eventhubs-eph-1.0.0.jar:na]
	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.lambda$updateLeaseInternal$23(AzureStorageCheckpointLeaseManager.java:748) ~[azure-eventhubs-eph-1.0.0.jar:na]
	... 10 common frames omitted
```

**Comment by warrenzhu25** [comment]
Can't reproduce
