### ISSUE TITLE
Spring cloud stream function with event hub binder not working

### ISSUE THREAD

**Issue by warrenzhu25** [Microsoft/spring-cloud-azure#384]
Used sample code here https://github.com/Microsoft/spring-cloud-azure/tree/spring-cloud-stream-function/spring-cloud-azure-samples/spring-cloud-azure-eventhub-binder-sample. Got following exception:

```
org.springframework.messaging.MessageDeliveryException: Dispatcher has no subscribers for channel 'application.input'.; nested exception is org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers, failedMessage=GenericMessage [payload=byte[11], headers={azure_partition_id=2, id=6cbe3fc3-a627-c5a0-4a24-c77e34a7b030, contentType=application/json, timestamp=1544682868210}]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:77) ~[spring-integration-core-5.1.0.RC2.jar:5.1.0.RC2]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:445) ~[spring-integration-core-5.1.0.RC2.jar:5.1.0.RC2]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:394) ~[spring-integration-core-5.1.0.RC2.jar:5.1.0.RC2]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.1.1.RELEASE.jar:5.1.1.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.1.1.RELEASE.jar:5.1.1.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.1.1.RELEASE.jar:5.1.1.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.1.1.RELEASE.jar:5.1.1.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:203) ~[spring-integration-core-5.1.0.RC2.jar:5.1.0.RC2]
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:45) ~[classes/:na]
	at com.microsoft.azure.spring.integration.eventhub.impl.EventHubProcessor.onEvents(EventHubProcessor.java:72) ~[classes/:na]
	at com.microsoft.azure.eventprocessorhost.PartitionPump.onReceive(PartitionPump.java:580) ~[azure-eventhubs-eph-1.0.0.jar:na]
	at com.microsoft.azure.eventhubs.impl.ReceivePump.run(ReceivePump.java:56) [azure-eventhubs-1.0.0.jar:na]
	at com.microsoft.azure.eventhubs.impl.PartitionReceiverImpl$5.run(PartitionReceiverImpl.java:209) [azure-eventhubs-1.0.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: org.springframework.integration.MessageDispatchingException: Dispatcher has no subscribers
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:139) ~[spring-integration-core-5.1.0.RC2.jar:5.1.0.RC2]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.1.0.RC2.jar:5.1.0.RC2]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.1.0.RC2.jar:5.1.0.RC2]
	... 13 common frames omitted
```

**Comment by warrenzhu25** [comment]
Adding `spring.cloud.stream.function.definition=toUpperCase` is fine.
