### ISSUE TITLE
Is the servicebus queue/topic binder not supporting session connections? The implementation class of 'ISessionHandler' cannot be found.

### ISSUE THREAD

**Issue by ScottZhangZC** [microsoft/spring-cloud-azure#514]
**Your issue may already be reported! Please search before creating a new one.**

## Current Behavior
* When I open a session connection in the Azure portal, my program reports an exception.
java.lang.UnsupportedOperationException: It is not possible for an entity that requires sessions to create a non-sessionful message receiver. TrackingId:ba008888-5792-4ca7-9f81-51c0a6445567_B12, SystemTracker:paase-test:Topic:paasse-topic|paasse-sub, Timestamp:2019-05-20T04:49:46 TrackingId:b4646c22bf784767bf72361a0f84072b_G10, SystemTracker:gateway7, Timestamp:2019-05-20T04:49:46
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:74) ~[azure-servicebus-1.2.8.jar:na]
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onError(CoreMessageReceiver.java:798) [azure-servicebus-1.2.8.jar:na]
	at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:973) [azure-servicebus-1.2.8.jar:na]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68) [azure-servicebus-1.2.8.jar:na]
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42) [azure-servicebus-1.2.8.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) [proton-j-0.31.0.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) [proton-j-0.31.0.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) [proton-j-0.31.0.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) [proton-j-0.31.0.jar:na]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:484) [azure-servicebus-1.2.8.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

## Possible Solution
* I guess  need the implementation class of 'ISessionHandler' to register, but I didn't find the implementation class of 'ISessionHandler', is there a sample reference?

## Branch
* placeholder

## Your Environment
* Version used: 
spring-cloud-azure-servicebus-queue-stream-binder 1.1.0.RC5
spring-cloud-azure-servicebus-topic-stream-binder 1.1.0.RC5
* Operating System and version (desktop or mobile):
* SDK version:

**Comment by warrenzhu25** [comment]
As I remember, we haven't provided session support. I'll confirm this. Come back to you later.

**Comment by esciullo** [comment]
I also need this feature, any update on this ? Thank you

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
