### ISSUE TITLE
HTTPS for Spring Cloud Azure Event Hub Stream Binder 1.0.0.M2

### ISSUE THREAD

**Issue by dsibilio** [microsoft/spring-cloud-azure#528]
## Expected Behavior
* The Spring Cloud Azure EventHub Stream Binder should make HTTP**S** requests against the Storage Account related APIs. It would be desirable by default, but it's important to note that this behaviour should be configurable.

## Current Behavior
* The Spring Cloud Azure EventHub Stream Binder release 1.0.0.M2 seems to only be making HTTP requests against the Storage Account related APIs. I can't find any property that would allow me to make HTTP**S** requests instead.

The following error is obtained:
`com.microsoft.azure.storage.StorageException: The account being accessed does not support http.
	at com.microsoft.azure.storage.StorageException.translateFromHttpStatus(StorageException.java:175)
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:94)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
	at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:769)
	at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:379)
	at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:348)
	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.lambda$createLeaseStoreIfNotExistsInternal$8(AzureStorageCheckpointLeaseManager.java:328)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

## Proposed Solution
* Is there a property that I don't know about that would allow me to make HTTP**S** requests instead? If so please share more information. If not, it would be nice to have HTTP**S** as default protocol in a version that's basically 1.0.0.M2 but with HTTPS as default protocol instead of HTTP. It is not possible for me to migrate to spring-cloud-azure-eventhub-stream-binder 1.1.X due to heavy dependency incompatibilities.

## Source Code
The class `com.microsoft.azure.spring.cloud.context.core.impl.StorageConnectionStringProvider.ConnectionStringBuilder` in the version 1.0.0.M2 has the following constant `private static final String HTTP_PROTOCOL = "http";` set, which causes the issue. Simply replacing its value with `"https"` instead, would solve this issue.

## Your Environment
* Version used: spring-cloud-azure-eventhub-stream-binder 1.0.0.M2
* Operating System and version (desktop or mobile): Windows 10 64-bit
* SDK version: Java(TM) SE Runtime Environment (build 1.8.0_74-b02)

**Comment by Mizaroth** [comment]
I've also opened [this](https://github.com/microsoft/spring-cloud-azure/pull/529) pull request with a potential solution when it comes down to offering the possibility to switch between http/https for Storage Account connection and checkpointing, in case you'd want to implement this functionality.

Of course it doesn't solve my problem with the older version 1.0.0.M2 where the default will still be set to "http" and still couldn't find any way to change it via configuration or bean overriding even.

**Comment by warrenzhu25** [comment]
Thanks for reporting this issue. I believe latest release `1.1.0.RC5` has already used `https` as default. If no breaking change, I'll suggest to upgrade to latest version

**Comment by dsibilio** [comment]
Sadly it is quite a demanding work for us to migrate to 1.1.0.RC5 at the moment, due to dependency issues. If it is not possible to backport this behaviour (default = https) to a version that's basically 1.0.0.M2 then I guess we'll hack it or patch it until we can safely upgrade to 1.1.0.RC5.
Thank you for your time :)
