### ISSUE TITLE
Reregister event hub consumer after unregister caused IllegalStateException

### ISSUE THREAD

**Issue by warrenzhu25** [microsoft/spring-cloud-azure#542]
# Steps to reproduce:
1. when the microservice starts all binders go up and … all is ok
2. after several tasks I decide to stop the binders and … all is ok
3. after some while I decide to restart the binders….I have a problem

# Stacktrace as below:
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalStateException: Register cannot be called on an EventProcessorHost after unregister. Please create a new EventProcessorHost instance.
Caused by: java.lang.IllegalStateException: Register cannot be called on an EventProcessorHost after unregister. Please create a new EventProcessorHost instance.
at com.microsoft.azure.eventprocessorhost.EventProcessorHost.registerEventProcessorFactory(EventProcessorHost.java:461)
at com.microsoft.azure.spring.integration.eventhub.impl.AbstractEventHubTemplate.register(AbstractEventHubTemplate.java:103)
at com.microsoft.azure.spring.integration.eventhub.impl.EventHubTemplate.subscribe(EventHubTemplate.java:40)
at com.microsoft.azure.spring.integration.core.api.SubscribeByGroupOperation.subscribe(SubscribeByGroupOperation.java:30)
at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.doStart(AbstractInboundChannelAdapter.java:38)
at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:156)
at org.springframework.cloud.stream.binder.DefaultBinding.start(DefaultBinding.java:116)
at com.wba.oneit.oneleo.config.BinderStartStopService.lambda$start$0(BinderStartStopService.java:41)
at java.util.concurrent.ConcurrentHashMap$EntrySetView.forEach(ConcurrentHashMap.java:4795)
at com.wba.oneit.oneleo.config.BinderStartStopService.start(BinderStartStopService.java:39)
```
# The root cause is inside:
```
protected void register(String name, String consumerGroup, EventHubProcessor eventProcessor) {
        EventProcessorHost host = this.clientFactory.getOrCreateEventProcessorHost(name, consumerGroup);
        host.registerEventProcessorFactory(context -> eventProcessor, buildEventProcessorOptions(startPosition));
    }

    protected void unregister(String name, String consumerGroup) {
        this.clientFactory.getOrCreateEventProcessorHost(name, consumerGroup).unregisterEventProcessor()
                          .whenComplete((s, t) -> {
                              if (t != null) {
                                  log.warn(String.format("Failed to unregister consumer '%s' with group '%s'", name,
                                          consumerGroup), t);
                              }
                          });
```
where this.clientFactory.getOrCreateEventProcessorHost is called in both register and unregister cases. 

But when I do the mentioned sequence of operations (register , unregister,  register)  I have an error during the second register phase because the EventProcessorHost retrieved from the map 
is registered and it has valorised variables that are null during the first register phase .

# How to fix

It seems that we should remove `EventProcessorHost` after unregister, then creating new one after reregister.

**Comment by dsibilio** [comment]
I've submitted a PR for this bug @ #546
