### ISSUE TITLE
java.lang.ClassCastException when getting nativeHeaders

### ISSUE THREAD

**Issue by yumingtao** [microsoft/spring-cloud-azure#592]
Hi All,

Dependencies:
spring-cloud-seluth-2.1.1.RELEASE
spring-cloud-azure-eventhubs-stream-binder-1.1.0.RC5

It is a Azure eventhub demo from azure docs(https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub) , which sent a message to eventhub and comsume it, I change the stream binder dependency to 1.1.0.RC5, but got below exception when comsuming data from eventhub. I debug it and find that when using sleuth, it will add nativeHeaders(eg.{X-B3-TraceId=[915f7baedd220522], spanTraceId=[915f7baedd220522], X-B3-SpanId=[980d03a075f5d148], spanId=[980d03a075f5d148], X-B3-ParentSpanId=[915f7baedd220522], spanParentSpanId=[915f7baedd220522], X-B3-Sampled=[0], spanSampled=[0]}) to the Meaasge object when send message to eventhub, and get exception in HeaderMethodArgumentResolver.getNativeHeaders when comsuming it.
I tried to use different spring-cloud-seluth and spring-cloud-stream version, but still have the issue, I must use spring-cloud-seluth for logging, so colud you please help to check it, thanks a lot.

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaders(HeaderMethodArgumentResolver.java:98) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaderValue(HeaderMethodArgumentResolver.java:85) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.resolveArgumentInternal(HeaderMethodArgumentResolver.java:69) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
at org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:100) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:147) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55) ~[spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]

The exception code in spring-messaging:
@SuppressWarnings("unchecked")
private Map<String, List> getNativeHeaders(Message<?> message) {
return (Map<String, List>) message.getHeaders().get(
NativeMessageHeaderAccessor.NATIVE_HEADERS);
}

But spring-cloud-azure-eventhubs-stream-binder-1.1.0.RC2 is compatible with sleuth. And for using azure 1.1.0.RC5, I add a global ChannelInterceptor and remove nativeHeaders in preSend() method as a workaround, I know it is not a good idea. But if is convenient, I want to know why it is incompatible for 1.1.0.RC5 and sleuth, thank a lot.

**Comment by saragluna** [comment]
Thanks for reaching out to us. We'll investigate it as soon as possible.

**Comment by yumingtao** [comment]
Hi,
The issue is still there when I upgrade the binder to 1.2.2

```
2020-03-11 13:28:48.873 ERROR [sc-eventhub,fb2711e7150d0ca6,7d04e42c7fb40b74,false] 69071 --- [9fad16c58]-1-14] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessagingException: Exception thrown while invoking com.ymt.sample.worker.DefaultListener#onEvent[2 args]; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map, failedMessage=GenericMessage [payload=byte[14], headers={azure_checkpointer=com.microsoft.azure.spring.integration.core.AzureCheckpointer@218b6217, azure_raw_partition_id=1, X-B3-ParentSpanId=5010e02a0788f66a, spanTraceId=fb2711e7150d0ca6, spanId=bdacc922b116a8c3, spanParentSpanId=5010e02a0788f66a, nativeHeaders={X-B3-TraceId=[fb2711e7150d0ca6], spanTraceId=[fb2711e7150d0ca6], X-B3-SpanId=[5010e02a0788f66a], spanId=[5010e02a0788f66a], X-B3-ParentSpanId=[fb2711e7150d0ca6], spanParentSpanId=[fb2711e7150d0ca6], X-B3-Sampled=[0], spanSampled=[0]}, X-B3-SpanId=bdacc922b116a8c3, X-B3-Sampled=0, X-B3-TraceId=fb2711e7150d0ca6, id=30982d72-7e7d-ad00-3362-d7d83b598ec1, spanSampled=0, contentType=application/json, timestamp=1583904528864}]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:63)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:169)
	at org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler.handleRequestMessage(DispatchingStreamListenerMessageHandler.java:81)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:162)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:205)
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:45)
	at com.microsoft.azure.spring.integration.eventhub.impl.EventHubProcessor.onEvents(EventHubProcessor.java:73)
	at com.microsoft.azure.eventprocessorhost.PartitionPump.onReceive(PartitionPump.java:493)
	at com.microsoft.azure.eventhubs.impl.ReceivePump$ProcessAndReschedule.apply(ReceivePump.java:167)
	at com.microsoft.azure.eventhubs.impl.ReceivePump$ProcessAndReschedule.apply(ReceivePump.java:155)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaders(HeaderMethodArgumentResolver.java:98)
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaderValue(HeaderMethodArgumentResolver.java:85)
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.resolveArgumentInternal(HeaderMethodArgumentResolver.java:69)
	at org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:100)
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:147)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	... 31 more

2020-03-11 13:28:48.879  WARN [sc-eventhub,,,] 69071 --- [9fad16c58]-1-14] c.m.a.eventprocessorhost.PartitionPump   : host capel0064841301.cn133.corpintra.net-ca81e3f8-d9fe-42a9-82aa-f529fad16c58: 1: Got exception from onEvents

org.springframework.messaging.MessagingException: Exception thrown while invoking com.ymt.sample.worker.DefaultListener#onEvent[2 args]; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:63) ~[spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:169) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.cloud.stream.binding.DispatchingStreamListenerMessageHandler.handleRequestMessage(DispatchingStreamListenerMessageHandler.java:81) ~[spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:162) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:401) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:205) ~[spring-integration-core-5.1.4.RELEASE.jar:5.1.4.RELEASE]
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:45) ~[spring-integration-azure-core-1.2.2.jar:1.2.2]
	at com.microsoft.azure.spring.integration.eventhub.impl.EventHubProcessor.onEvents(EventHubProcessor.java:73) ~[spring-integration-eventhubs-1.2.2.jar:1.2.2]
	at com.microsoft.azure.eventprocessorhost.PartitionPump.onReceive(PartitionPump.java:493) ~[azure-eventhubs-eph-2.4.0.jar:na]
	at com.microsoft.azure.eventhubs.impl.ReceivePump$ProcessAndReschedule.apply(ReceivePump.java:167) [azure-eventhubs-2.2.0.jar:na]
	at com.microsoft.azure.eventhubs.impl.ReceivePump$ProcessAndReschedule.apply(ReceivePump.java:155) [azure-eventhubs-2.2.0.jar:na]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) [na:1.8.0_131]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) [na:1.8.0_131]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [na:1.8.0_131]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaders(HeaderMethodArgumentResolver.java:98) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.getNativeHeaderValue(HeaderMethodArgumentResolver.java:85) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.annotation.support.HeaderMethodArgumentResolver.resolveArgumentInternal(HeaderMethodArgumentResolver.java:69) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:100) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:147) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55) ~[spring-cloud-stream-2.1.0.RELEASE.jar:2.1.0.RELEASE]
	... 31 common frames omitted
```

**Comment by saragluna** [comment]
@yumingtao 

Could you help provide the minimal samples for me to reproduce the exceptions?

**Comment by yumingtao** [comment]
> @yumingtao
> 
> Could you help provide the minimal samples for me to reproduce the exceptions?

Hi ,  I pushed the code in github, it is https://github.com/yumingtao/spring-cloud-azure-eventhub-binder-example , thanks.

**Comment by yumingtao** [comment]
@saragluna 
This is the issue I create in spring cloud last year, FYI...
https://github.com/spring-cloud/spring-cloud-sleuth/issues/1503

**Comment by saragluna** [comment]
@yumingtao 

Thanks for your update, will look into it soon.

**Comment by yumingtao** [comment]
@saragluna  Hello, the issue is still there, I can't use the latest version. Any progress for this topic, thanks.

**Comment by moarychan** [comment]
hi @yumingtao , PR is comming, in addition, I want to know, how will you use it after getting a nativeHeader value?

**Comment by yumingtao** [comment]
> hi @yumingtao , PR is comming, in addition, I want to know, how will you use it after getting a nativeHeader value?

Hello @saragluna, just saw your comment, actually, I use the tracking id and span id which generated by sleuth to track the invoke chain and do log analysis in EFK, these ids are cross-passed by native-headers, thank you for fixing it.

**Comment by yiliuTo** [comment]
Hi @yumingtao , has the issue been solved? If so, shall we close it?

**Comment by yumingtao** [comment]
> Hi @yumingtao , has the issue been solved? If so, shall we close it?

@yiliuTo I want to confirm which version I should use, 1.2.7 from maven central repository?

**Comment by moarychan** [comment]
@yumingtao 1.2.7 unresolved. Please use 1.2.8, which is expected to be released in 6 weeks. Maybe you can compile a temporary version yourself.

**Comment by moarychan** [comment]
@yumingtao please try to use the 1.2.8-SNAPSHOT. follow this link:https://github.com/microsoft/spring-cloud-azure#snapshots

**Comment by sarathn91** [comment]
I'm using 1.2.8 and still the same issue as OP.

**Comment by saragluna** [comment]
@sarathn91 we've deprecated this repo, could you please file an issue [here](https://github.com/Azure/azure-sdk-for-java/issues)?
