### ISSUE TITLE
Can not connect to China Azure eventhub via SpringBoot

### ISSUE THREAD

**Issue by yumingtao** [microsoft/spring-cloud-azure#593]
Hi All,

Dependencies:
spring-boot 2.1.4.RELEASE
spring-cloud-azure-eventhubs-stream-binder-1.1.0.RC2

Also the same Azure eventhub demo from azure docs(https://docs.microsoft.com/en-us/azure/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub), but use connection string not credential file connecting to eventhub, and the configuration like below.

```
spring.cloud.azure.resource-group=[eventhub_rg]
spring.cloud.azure.environment=CHINA
spring.cloud.azure.eventhub.namespace=[eventhub-na]

spring.cloud.azure.eventhub.connection-string=[endpoint_from_azure_portal]
spring.cloud.azure.eventhub.checkpoint-access-key=[access_key_from_azure_portal]
spring.cloud.azure.eventhub.checkpoint-storage-account=[storage_account]
spring.cloud.stream.eventhub.bindings.input.consumer.checkpoint-mode=MANUAL

spring.cloud.stream.bindings.input.destination=[eventhub_name]
spring.cloud.stream.bindings.input.group=$Default
spring.cloud.stream.bindings.output.destination=[eventhub_mame]
```

When starting the demo, got exception:

```
com.microsoft.azure.storage.StorageException: The client could not finish the operation within specified maximum execution timeout.
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:243) ~[azure-storage-8.0.0.jar:na]
	at com.microsoft.azure.storage.blob.CloudBlobContainer.exists(CloudBlobContainer.java:744) ~[azure-storage-8.0.0.jar:na]
	at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:354) ~[azure-storage-8.0.0.jar:na]
	at com.microsoft.azure.storage.blob.CloudBlobContainer.createIfNotExists(CloudBlobContainer.java:323) ~[azure-storage-8.0.0.jar:na]
	at com.microsoft.azure.eventprocessorhost.AzureStorageCheckpointLeaseManager.createLeaseStoreIfNotExists(AzureStorageCheckpointLeaseManager.java:233) ~[azure-eventhubs-eph-2.4.0.jar:na]
	at com.microsoft.azure.eventprocessorhost.PartitionManager.lambda$initializeStores$11(PartitionManager.java:185) [azure-eventhubs-eph-2.4.0.jar:na]
	at com.microsoft.azure.eventprocessorhost.PartitionManager.lambda$buildRetries$16(PartitionManager.java:225) [azure-eventhubs-eph-2.4.0.jar:na]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[na:1.8.0_131]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[na:1.8.0_131]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[na:1.8.0_131]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: java.util.concurrent.TimeoutException: The client could not finish the operation within specified maximum execution timeout.
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:242) ~[azure-storage-8.0.0.jar:na]
	... 17 common frames omitted

2019-12-10 13:25:50.796  WARN [sc-eventhub,,,] 39515 --- [c4cb0258bc]-1-9] c.m.a.e.PartitionManager                 : host capel0064841301.cn133.corpintra.net-56c2e9a1-9f73-4c82-bac0-82c4cb0258bc: Failure creating lease store for this Event Hub, retrying
```

I debug the code, and found the DefaultEnvironmentProvider gave the environment as GLOBAL and the demo tried to connnect to core.windows.net not core.chinacloudapi.cn, so can not connect to eventhub and time out. But I configured spring.cloud.azure.environment=CHINA in properties, but it is ineffective, could you please help to check if I missing some configuration or configured wrong? Thanks a lot.

```
public class DefaultEnvironmentProvider implements EnvironmentProvider {
    private Environment environment = Environment.GLOBAL;

    @Override
    public Environment getEnvironment() {
        return environment;
    }

    public void setEnvironment(@NonNull Environment environment) {
        this.environment = environment;
    }
}
```

And my currently workaround is, create a ChinaEnvironmentProvider in the demo, then it works, but it is not a good idea, the environment should come from configuration.
```
@Component
public class ChinaEnvironmentProvider implements EnvironmentProvider {

    private Environment environment = Environment.CHINA;

    @Override
    public Environment getEnvironment() {
        return environment;
    }

    public void setEnvironment(@NonNull Environment environment) {
        this.environment = environment;
    }
}
```

**Comment by saragluna** [comment]
Thanks for reporting it and we'll look into it.

**Comment by yumingtao** [comment]
Hi,

The issue is still there, it is not support spring.cloud.azure.environment=AZURE_CHINA when upgrade the binder to 1.2.2

**Comment by saragluna** [comment]
@yumingtao 

Sorry for the late response.  We've upgraded our Event Hub libraries to the latest version on our master branch and there's a [snapshot version ](https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/azure/spring-cloud-azure-eventhubs-stream-binder/1.2.3-SNAPSHOT/)you could try with. I've tested the binder sample using our code on the master branch, against the AZURE_CHINA endpoints and it worked. Just autowire an Environment bean as you provided above:

```java
@Bean
    public EnvironmentProvider environmentProvider() {
        // or implement your environment provider
        DefaultEnvironmentProvider mooncakeEnvironmentProvider = new DefaultEnvironmentProvider();
        mooncakeEnvironmentProvider.setEnvironment(AzureEnvironment.AZURE_CHINA);

        return mooncakeEnvironmentProvider;
    }
```
By the way, we're planning a release next week. Let me know if you encounter any further problems.

**Comment by saragluna** [comment]
No update on this issue so close it now.
