### ISSUE TITLE
service-bus: manual checkpoint with sessions queue throws UnsupportedOperationException: Receiver not created. Registering a MessageHandler creates a receiver.

### ISSUE THREAD

**Issue by gennadiy-dubina** [microsoft/spring-cloud-azure#594]
When i use sessions enabled queue template with manual azure checkpoint and try to mark message as success or failed it throws `java.lang.UnsupportedOperationException: Receiver not created. Registering a MessageHandler creates a receiver`

Part stack trace
```
Caused by: java.lang.UnsupportedOperationException: Receiver not created. Registering a MessageHandler creates a receiver.
	at com.microsoft.azure.servicebus.MessageAndSessionPump.checkInnerReceiveCreated(MessageAndSessionPump.java:829)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.completeAsync(MessageAndSessionPump.java:711)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.completeAsync(MessageAndSessionPump.java:706)
	at com.microsoft.azure.servicebus.QueueClient.completeAsync(QueueClient.java:338)
	at com.microsoft.azure.spring.integration.servicebus.queue.ServiceBusQueueTemplate$QueueMessageHandler.success(ServiceBusQueueTemplate.java:118)
	at com.microsoft.azure.spring.integration.servicebus.ServiceBusMessageHandler.lambda$onMessageAsync$0(ServiceBusMessageHandler.java:48)
	at com.microsoft.azure.spring.integration.core.AzureCheckpointer.success(AzureCheckpointer.java:31)

```

## Expected Behavior
* no exception

## Current Behavior
* throws exemption `java.lang.UnsupportedOperationException: Receiver not created. Registering a MessageHandler creates a receiver`

## Steps to Reproduce (for bugs)
* create `ServiceBusQueueTemplate` bean
* enable sessions
```
template.setClientConfig(ServiceBusClientConfig.builder()
                .setConcurrency(concurrency)
                .setPrefetchCount(prefetchCount)
                .setSessionsEnabled(true)
                .build());
```
* build connector with manual checkpoint
```
public static ServiceBusQueueInboundChannelAdapter createChannelAdapter(String queueName,
                                                                            MessageChannel inputChannel,
                                                                            ServiceBusQueueOperation queueOperation) {
        queueOperation.setCheckpointConfig(CheckpointConfig.builder().checkpointMode(CheckpointMode.MANUAL).build());
        ServiceBusQueueInboundChannelAdapter adapter = new ServiceBusQueueInboundChannelAdapter(queueName, queueOperation);
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }
```
* receive message and try to commit it
```
private void commit(String message, Checkpointer checkpointer) {
        checkpointer.success().handle((r, ex) -> {
            if (ex != null) {
                log.error("Can not checkpoint message: {}", message, ex);
            } else {
                log.debug("Successfully checkpoint message: {}", message);
            }
            return null;
        });
    }
```

## Branch
* version 1.2.0

## Your Environment
* Version used: 1.2.0
* Operating System and version (desktop or mobile): windows 10, java 11, spring boot 2.2.2
* SDK version: 3.1.1

**Comment by gennadiy-dubina** [comment]
the same issue without changing checkpoint

```
java.lang.UnsupportedOperationException: Receiver not created. Registering a MessageHandler creates a receiver.
	at com.microsoft.azure.servicebus.MessageAndSessionPump.checkInnerReceiveCreated(MessageAndSessionPump.java:829)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.completeAsync(MessageAndSessionPump.java:711)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.completeAsync(MessageAndSessionPump.java:706)
	at com.microsoft.azure.servicebus.QueueClient.completeAsync(QueueClient.java:338)
	at com.microsoft.azure.spring.integration.servicebus.queue.ServiceBusQueueTemplate$QueueMessageHandler.success(ServiceBusQueueTemplate.java:118)
	at com.microsoft.azure.spring.integration.servicebus.ServiceBusMessageHandler.lambda$onMessageAsync$0(ServiceBusMessageHandler.java:48)
	at com.microsoft.azure.spring.integration.core.AzureCheckpointer.success(AzureCheckpointer.java:31)
	at com.microsoft.azure.spring.integration.servicebus.ServiceBusMessageHandler.onMessageAsync(ServiceBusMessageHandler.java:58)
	at com.microsoft.azure.spring.integration.servicebus.queue.ServiceBusQueueTemplate$QueueMessageHandler.onMessageAsync(ServiceBusQueueTemplate.java:140)
	at com.microsoft.azure.servicebus.MessageAndSessionPump.lambda$null$9(MessageAndSessionPump.java:329)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

code 
```
public static ServiceBusQueueInboundChannelAdapter createChannelAdapterNoCheckpoint(String queueName, MessageChannel inputChannel, ServiceBusQueueOperation queueOperation) {
        ServiceBusQueueInboundChannelAdapter adapter = new ServiceBusQueueInboundChannelAdapter(queueName, queueOperation);
        adapter.setOutputChannel(inputChannel);
        return adapter;
    }
```

**Comment by saragluna** [comment]
Thanks for reporting it. We'll look into this and come back to you later.

**Comment by gennadiy-dubina** [comment]
@esciullo can you help with this? do you have real example of `ServiceBusQueueTemplate` with `isSessionsEnabled` ?

**Comment by esciullo** [comment]
@saragluna could be related to https://github.com/Azure/azure-docs-sdk-java/issues/373 ?

**Comment by gennadiy-dubina** [comment]
@esciullo but i don't have a solution there

**Comment by esciullo** [comment]
@gennadiy-dubina could you share a repo with your code ?

**Comment by gennadiy-dubina** [comment]
@esciullo unfortunately, it's a private

**Comment by gennadiy-dubina** [comment]
steps is trivial
1. create `ServiceBusQueueTemplate`
2. create consumer
```
ServiceBusQueueInboundChannelAdapter adapter = new ServiceBusQueueInboundChannelAdapter(queueName, queueOperation);
        adapter.setOutputChannel(inputChannel);
```
it's enough to reproduce an issue

**Comment by gennadiy-dubina** [comment]
@saragluna any update with it?
do you have any workaround ?

**Comment by esciullo** [comment]
Fixed with this pull request https://github.com/microsoft/spring-cloud-azure/pull/596

**Comment by gennadiy-dubina** [comment]
@saragluna @esciullo do you any expectations about new release with this fix?

**Comment by gennadiy-dubina** [comment]
Hi @neuqlz 
Can we expect this PR will merged and released?
Or do we need to make fork and build custom lib version? 

Thanks,

**Comment by neuqlz** [comment]
Hi @gennadiy-dubina, sorry for the late reply.
Yes, the PR will be merged after my review, I will do it right now. Please stay tunned.

**Comment by neuqlz** [comment]
Hi @gennadiy-dubina, sorry for the late reply.
Yes, the PR will be merged after my review, I will do it right now. Please stay tuned.

**Comment by neuqlz** [comment]
By the way, according to our release train, the next release will be at five weeks later. Before that, you can use the SNAPSHOT version in advance.

**Comment by gennadiy-dubina** [comment]
hi @neuqlz 
we have switched to SNAPSHOT version and now it can send and receive messages from session queue

but we have got another issues
1. Delivery counter is not increased on event redelivery and event is redelivered each minute
2. Configured lock time is ignored for redelivery, event is redelivered each minute even lock time is configured to 5 min

is it expected? 

Thanks,
