### ISSUE TITLE
Eventhub sample cannot start successfully if EventHub input destination is not created ahead

### ISSUE THREAD

**Issue by sophiaso** [Microsoft/spring-cloud-azure#68]
## Expected Behavior
* When all resources are not existings, EventHub sample should create all required resources and the application starts successfully

## Current Behavior
* EventHub example fails to start with exception.
```
org.springframework.cloud.stream.provisioning.ProvisioningException: Event hub with name 'xxx-eventhub-input-destination' in namespace 'xxx-eventhub' not existed
	at com.microsoft.azure.eventhub.stream.binder.provisioning.EventHubChannelProvisioner.provisionConsumerDestination(EventHubChannelProvisioner.java:50) ~[classes/:na]
	at com.microsoft.azure.eventhub.stream.binder.provisioning.EventHubChannelProvisioner.provisionConsumerDestination(EventHubChannelProvisioner.java:23) ~[classes/:na]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:274) ~[spring-cloud-stream-2.0.0.RC3.jar:2.0.0.RC3]
	.........more
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) ~[spring-boot-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at com.example.EventHubBinderApplication.main(EventHubBinderApplication.java:19) ~[classes/:na]
```
```
2018-07-10 15:15:02.267 ERROR 201284 --- [ask-scheduler-1] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.provisioning.ProvisioningException: Event hub with name 'xxx-eventhub-input-destination' in namespace 'xxx-eventhub' not existed
	at com.microsoft.azure.eventhub.stream.binder.provisioning.EventHubChannelProvisioner.provisionConsumerDestination(EventHubChannelProvisioner.java:50) ~[classes/:na]
	at com.microsoft.azure.eventhub.stream.binder.provisioning.EventHubChannelProvisioner.provisionConsumerDestination(EventHubChannelProvisioner.java:23) ~[classes/:na]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:274) ~[spring-cloud-stream-2.0.0.RC3.jar:2.0.0.RC3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:77) ~[spring-cloud-stream-2.0.0.RC3.jar:2.0.0.RC3]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:129) ~[spring-cloud-stream-2.0.0.RC3.jar:2.0.0.RC3]
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleConsumerBinding$0(BindingService.java:154) ~[spring-cloud-stream-2.0.0.RC3.jar:2.0.0.RC3]
	..........more
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
```

**Comment by warrenzhu25** [comment]
`input.destination` should be same with `output.destination`. Will update in the doc
