### ISSUE TITLE
org.springframework.core.convert.ConverterNotFoundException: AzureCheckpointer 

### ISSUE THREAD

**Issue by Nobuyuki-Inaba** [microsoft/spring-cloud-azure#697]
Hi,  
I  did following the article. [How to create a Spring Cloud Stream Binder application with Azure Event Hubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub)

I found out spring-cloud-azure-eventhubs-stream-binder#1.1.0.RC2 is used in the article. The dependency seems old. Because of that, I changed the version to 1.1.4 but  ConverterNotFoundException occured after that. 1.1.2 works fine, As of 1.1.3 doesn't work.

I changed the code ( refer the below Possible Solution Code ) to work, but I don't believe the change is correct.
Could you tell me how to use  spring-cloud-azure-eventhubs-stream-binder#1.1.3 or later.

## Expected Behavior
* sample source code using the version spring-cloud-azure-eventhubs-stream-binder#1.1.3  or later, works fine.

## Current Behavior
* The below Exception occured.
```
2020-05-12 19:54:53.049  INFO 12764 --- [           main] c.e.s.SpringcloudeventhubApplication     : Started SpringcloudeventhubApplication in 18.476 seconds (JVM running for 18.95)
2020-05-12 19:54:55.074  INFO 12764 --- [ctor-http-nio-1] c.m.a.s.i.e.impl.EventHubProcessor       : Started receiving on partition: 1
2020-05-12 19:55:00.713  INFO 12764 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-05-12 19:55:00.713  INFO 12764 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-05-12 19:55:00.718  INFO 12764 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 5 ms
2020-05-12 19:55:01.391 ERROR 12764 --- [      elastic-4] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessagingException: Exception thrown while invoking EventhubSink#handleMessage[2 args]; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.microsoft.azure.spring.integration.core.api.reactor.AzureCheckpointer] to type [@org.springframework.messaging.handler.annotation.Header com.microsoft.azure.spring.integration.core.api.Checkpointer], failedMessage=GenericMessage [payload=byte[5], headers={id=ac9335ef-3ac2-8647-3209-930b0a01c6e2, contentType=application/json, azure_checkpointer=com.microsoft.azure.spring.integration.core.api.reactor.AzureCheckpointer@61da2afc, azure_raw_partition_id=1, timestamp=1589280901370}]
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:64)
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:127)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:177)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:198)
	at com.microsoft.azure.spring.integration.core.AbstractInboundChannelAdapter.receiveMessage(AbstractInboundChannelAdapter.java:45)
	at com.microsoft.azure.spring.integration.eventhub.impl.EventHubProcessor.onEvent(EventHubProcessor.java:77)
	at com.azure.messaging.eventhubs.EventProcessorClientBuilder$1.processEvent(EventProcessorClientBuilder.java:353)
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:178)
	at com.azure.messaging.eventhubs.PartitionPumpManager.lambda$startPartitionPump$1(PartitionPumpManager.java:148)
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:203)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:439)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:526)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.microsoft.azure.spring.integration.core.api.reactor.AzureCheckpointer] to type [@org.springframework.messaging.handler.annotation.Header com.microsoft.azure.spring.integration.core.api.Checkpointer]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194)
	at org.springframework.messaging.handler.annotation.support.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:118)
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:148)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	... 31 more
```

## Possible Solution
* Change com.microsoft.azure.spring.integration.core.api.Checkpointer to com.microsoft.azure.spring.integration.core.AzureCheckpointer

I couldn't find out any documents which explaining how to use AzureCheckpointer class.
If you know where the document, please tell me.

## Snapshot Code for Reproduce 
https://github.com/Nobuyuki-Inaba/azure-spring-cloud-stream

## Your Environment
* zulu11.39.15-ca-jdk11.0.7-win_x64
* Azure environment (EventHub storage account)

**Comment by yiliuTo** [comment]
Hi, you can refer to the sample in this spring-cloud-azure repo: [https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/eventhubs-binder-sample](url). This sample uses eventhub binder and can work well.

**Comment by Nobuyuki-Inaba** [comment]
Hi, Thank for your quick reply.
Thanks the sample code, The issue is fixed.

The wrong point was CheckPointer package. com.microsoft.azure.spring.integration.core.api.reactor.Checkpointer is correct.
I believe that as of 1.1.3 something is changed.

**Comment by saragluna** [comment]
Yes, we upgrade underlying Event Hubs SDK, which uses reactor implementation.

**Comment by Nobuyuki-Inaba** [comment]
Hi,
Thanks, you've convinced me.
