### ISSUE TITLE
Service Bus uses oauth2 implementation that conflicts with Azure SDK

### ISSUE THREAD

**Issue by mrm9084** [microsoft/spring-cloud-azure#713]
spring-cloud-azure-servicebus-topic-stream-binder has a dependency on oauth2-oidc-sdk 5.64.4 through the Azure Java Client Authentication library. This conflicts with the Azure Java SDK azure-identity library which uses oauth2-oidc-sdk 6.14.

This causes an ClassCastException when using both.

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:101)
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:159)
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

## Expected Behavior
* Azure libraries should not conflict with each other

## Current Behavior
* Library conflict causes error.

## Possible Solution
* the library should use the new azure SDK

## Steps to Reproduce (for bugs)
* Use both the azure-identity and spring-cloud-azure-servicebus-topic-stream-binder

## Branch
* master

**Comment by yiliuTo** [comment]
Hi @mrm9084 , the oauth2-oidc-sdk (5.64.4) dependency in the starter is imported from azure-servicebus library and we depend on its track 1 version. Currently we are waiting when azure-servicebus releases a GA and then we could depend on its track 2 version which will resolve the version conflict.

For this issue, do you use the features in oauth2-oidc-sdk(6.14) in the code? If not maybe you can try to exclude oauth2-oidc-sdk library when depend on azure-identity.

**Comment by mrm9084** [comment]
@yiliuTo I have found a way to make it work, not sure why it does. So my setup uses both the Azure SDK for Java for Identity to App Configuration and Bus Topics for notifying for refresh events. So I am using, spring-cloud-bus, spring-cloud-azure-servicebus-topic-stream-binder, and azure-identity.

With this setup you can make it work if you do the following:

1. Use a credential-file-path, not the connection string
1. **Don't** set the spring.cloud.azure.resource-group value
1. Along with setting:
spring.cloud.stream.bindings.input.destination=[servicebus-topic-name]
spring.cloud.stream.bindings.input.group=[topic-subscription-name]
spring.cloud.stream.bindings.output.destination=[servicebus-topic-name-same-as-above]

you also need to set:
spring.cloud.stream.bindings.springCloudBusInput.destination=[servicebus-topic-name]
spring.cloud.stream.bindings.springCloudBusInput.group=[topic-subscription-name]
spring.cloud.stream.bindings.springCloudBusOutput.destination=[servicebus-topic-name-same-as-above]

If you set all of that it works fine.

**Comment by yiliuTo** [comment]
Thanks a lot~ @mrm9084

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
