### ISSUE TITLE
Azure context - NullPointerException due to wrong check when MSI is enabled (region is checked instead of subscription id)

### ISSUE THREAD

**Issue by avpines** [microsoft/spring-cloud-azure#756]
When MSI is enabled even though region is not mandatory, validation accidentally checks for it instead of subscription-id. In `AzureProperties.java`:

```
if (msiEnabled && Strings.isNullOrEmpty(subscriptionId)) {
    Assert.hasText(this.region, "When msi is enabled, spring.cloud.azure.subscription-id must be provided");
}
````

The assertion should use the subscription id instead of region:

```
Assert.hasText(this.subscriptionId, "When msi is enabled, spring.cloud.azure.subscription-id must be provided");
````

This causes a `NullPointerException` when region is not given.

```
Caused by: java.lang.NullPointerException: null
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.ServiceBusUtils.getNamespace(ServiceBusUtils.java:12)
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusQueueAutoConfiguration.queueClientFactory(AzureServiceBusQueueAutoConfiguration.java:60)
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusQueueAutoConfiguration$$EnhancerBySpringCGLIB$$41f13fa0.CGLIB$queueClientFactory$1(<generated>)
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusQueueAutoConfiguration$$EnhancerBySpringCGLIB$$41f13fa0$$FastClassBySpringCGLIB$$f041ed51.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
    at com.microsoft.azure.spring.cloud.autoconfigure.servicebus.AzureServiceBusQueueAutoConfiguration$$EnhancerBySpringCGLIB$$41f13fa0.queueClientFactory(<generated>)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
    ... 58 common frames omitted
```

**Comment by zhoufenqin** [comment]
Hi @avpines, the repo has been migrated to https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring, could you please create the issue there? should fill more issue details in azure-sdk-for-java repo

**Comment by avpines** [comment]
Sure @zhoufenqin - created https://github.com/Azure/azure-sdk-for-java/issues/15435
