### ISSUE TITLE
After upgrading to Spring Boot 2.4, kafka binder stopped working: NoClassDefFoundError: com.nimbusds.oauth2.sdk.http.CommonContentTypes

### ISSUE THREAD

**Issue by vprudnikov** [microsoft/spring-cloud-azure#763]
Hello,

I upgraded my app:
* Spring boot 2.3 -> Spring Boot 2.4
* spring-cloud-starter-azure-eventhubs-kafka:1.2.7 -> azure-spring-cloud-starter-eventhubs-kafka:2.0.0-beta.1

After that, the app stopped working because of app context failure:

```
Caused by: java.lang.NoClassDefFoundError: com.nimbusds.oauth2.sdk.http.CommonContentTypes
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:158) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:86) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:930) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.4.jar:1.6.4]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.4.jar:1.6.4]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:851) ~[na:na]
Caused by: java.lang.ClassNotFoundException: com.nimbusds.oauth2.sdk.http.CommonContentTypes
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:788) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1081) ~[na:na]
	... 10 common frames omitted
```

Thank you in advance for help!

**Comment by chenrujun** [comment]
@vprudnikov .
Sorry that spring-boot-2.4 is not supported yet. Please wait for next release.

**Comment by saragluna** [comment]
@vprudnikov we've deprecated this repo and migrated our projects to this one https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring. I'll close this issue here and create one in the azure-sdk-for-java repo.

**Comment by saragluna** [comment]
Closing this issue now in favor of https://github.com/Azure/azure-sdk-for-java/issues/18929
